### ISSUE TITLE
Negation of external module calls. "ERROR IN TRANSLATE"

### ISSUE THREAD

**Issue by HelenHarman** [speckdavid/shakey2016#4]
Hi David,

When attempting to use "not" in a PDDL condition containing a call to an external module I get: 
> assert not negated
> AssertionError
> ERROR IN TRANSLATE

The full error message when I run https://github.com/speckdavid/shakey2016/blob/master/gki_symbolic_planning/planner_benchmarks/modular/negated-modules/domain-negated.pddl is:
>process[tfdplan-1]: started with pid [26122]
Parsing...
Parsing durative-action inc
Traceback (most recent call last):
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/translate.py", line 1014, in <module>
    task = pddl.open()
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/pddl_file.py", line 44, in open
    return tasks.Task.parse(domain_pddl, task_pddl)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/tasks.py", line 50, in parse
    = parse_domain(domain_pddl)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/tasks.py", line 281, in parse_domain
    parse_domain_structure(entry,the_functions,the_axioms,the_actions,the_durative_actions,the_types,the_predicates)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/tasks.py", line 196, in parse_domain_structure
    action = actions.DurativeAction.parse(entry)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/actions.py", line 168, in parse
    condition = conditions.parse_durative_condition(iterator.next())
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/conditions.py", line 71, in parse_durative_condition
    parts = [parse_durative_condition(part) for part in args]
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/conditions.py", line 90, in parse_durative_condition
    condition = parse_condition_aux(alist[2], False)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/conditions.py", line 28, in parse_condition_aux
    return parse_condition_aux(args[0], not negated)
  File "/home/helen/Documents/ros_libs/shakey_ws/src/shakey/gki_symbolic_planning/tfd_modules/downward/translate/pddl/conditions.py", line 34, in parse_condition_aux
    assert not negated
AssertionError
ERROR IN TRANSLATE

Kind regards,
Helen

**Comment by dornhege** [comment]
Hi Helen,

short answer: Just put the Not inside the module, i.e., implement it to return the inverse result.

longer answer: This is caused by TFD/M. Although it is technically possible to negate modules, we assert this case to prevent it from happening. The reason is an additional feature that has been added for performance that would require an extended module interface and implementation for negated modules as otherwise with this enabled the search would loose soundness.

Best,
  Christian

**Comment by HelenHarman** [comment]
Hi Christian,

Thank you for the response. 
I have added an inverse function.

Best,
Helen
